config/routes.rb
Rails.application.routes.draw do

  get 'bloods/new'
  get 'bloods/find'
   get 'bloods/show'

  post 'bloods/find'
  post 'bloods/show'
  post 'welcome/create'

  resources :bloods, :only => [ :show,:create]

  get 'welcome/index'

   root 'welcome#index'

end

app/models/blooddb.rb
class Blooddb < ActiveRecord::Base

  validates :firstname,:lastname,:email_id,:gender,:dob,:mobno,:bloodgrp,:address,:state,:city,:pincode, presence: true
  validates :email_id, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}, uniqueness:true
  validates :mobno,uniqueness: true






end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :name,:number,:email_id,:text, presence: true
  validates :email_id, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bloods_controller.rb
class BloodsController < ApplicationController
  def new
    @blood = Blooddb.new

  end

  def create
    @blood = Blooddb.new(params.require(:blooddb).permit(:firstname, :lastname,:email_id,:gender,:dob,:bloodgrp,:mobno,:address,:state,:city,:pincode))

    if @blood.save
      redirect_to "http://localhost:3000/bloods/new"
    else
      render 'new'
    end
  end
  def find

  end

  def show

    #@blood = Blooddb.new(params.require(:blooddb).permit(:bloodgrp,:state))

     @bloods=Blooddb.where(params.require(:blooddb).permit(:bloodgrp,:state))



  end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      @comment=Comment.new
  end
  def create

    @comment = Comment.new(params.require(:comment).permit(:name,:email_id,:number,:text))

    if @comment.save
      redirect_to "http://localhost:3000/"
    else
      redirect_to "http://localhost:3000/"
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloods_helper.rb
module BloodsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bloods/find.html.erb
<html>
<body>


<h1 class="head"> Search For Blood Donor</h1>

<style>
  .find_div
  {

    margin-left: 550px;
      margin-top:150px;
      border-radius: 25px;
      border: 2px solid #ac2925;
      background: #a6e1ec;
      padding: 20px;
      width: 270px;
      height: 250px;



  }
        .head
        {
            
            font-weight: bolder;
            font-size: 40px;
        }
  .home{

      margin-left:950px;
      margin-top: 40px;
      font-weight: bold;
      font-size: large;
      font-style: inherit;
  }
  </style>
<a class="home" href="http://localhost:3000">Home</a>
<div class="find_div">
  <%= form_for :blooddb  , url: {action: "show"} do |f| %>

      <label >BloodGroup:</label>
     <br>
      <br>
      <%= f.select :bloodgrp, options_for_select(%w[A+ A- B+ B- AB+ AB- O+ O- A1+ A1- A2+ A2- A1B+ A1B- A2B+ A2B- BombayBloodGroup]) %>

       <br>
      <br>
      <label >State:</label>
      <br>
      <br>
        <%= f.select :state, options_for_select(%w[AndamanandNicobarIslands
      AndhraPradesh
      ArunachalPradesh
      Assam
      Bihar
      Chandigarh
      Chhattisgarh
      DadraandNagar Haveli
      DamanandDiu
      Delhi
      Goa
      Gujarat
      Haryana
      HimachalPradesh
      JammuandKashmir
      Jharkhand
      Karnataka
      Kerala
      Lakshadweep
      MadhyaPradesh
      Maharashtra
      Manipur
      Meghalaya
      Mizoram
      Nagaland
      Odisha
      Puducherry
      Punjab
      Rajasthan
      Sikkim
      TamilNadu
      Telengana
      Tripura
      UttarPradesh
      Uttarakhand
      WestBengal

      ]) %>

      <br>
       <br>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.submit(value='Find')%>




      </div>

  <% end %>
        </body>
</html>

app/views/bloods/new.html.erb
<html>
<body>

<h1>Blood Donor Registration Form</h1>
<style>
  h1 {
  margin-left: 70px;
  }
  form li {
  list-style: none;
  margin-bottom: 5px;
  }

  form ul li label{

  float: left;
  clear: left;
  width: 100px;
  text-align: right;
  margin-right: 10px;
  font-family:Verdana, Arial, Helvetica, sans-serif;
  font-size:14px;
  }

  form ul li input, select, span {
  float: left;
  margin-bottom: 10px;
  }

  form textarea {

  float: left;
  width: 350px;
  height: 150px;
  }

  [type="submit"] {
      clear: left;
      margin: 420px 200px 0 290px;
      font-size:18px
  }

  p {
  margin-left: 70px;
  font-weight: bold;
  }
.regform
{
    margin-left: 300px;
    margin-right: 150px;
    margin-inside: 10px;
    background-color: #a6e1ec;

}
        .home{
            
            margin-left:800px;
            margin-top: 100px;
            font-weight: bold;
            font-size: large;
            font-style: inherit;
        }
        .error
        {




            margin-left: 900px;
            margin-top:-600px;
            color:#B00100;

        }

</style>



<div class="regform">
  <a class="home" href="http://localhost:3000">Home</a>
<%= form_for :blooddb  ,url: bloods_path do |f| %>




   <ul>
    <li><label for="firstname">FirstName</label></li>
    <li><%= f.text_field :firstname,:size=>30,:maxlength=>15 %></li>
     <li></li>
    <li><label for="lastname">LastName:</label></li>
    <li><%= f.text_field :lastname,:size=>30,:maxlength=>15 %></li>
     <li></li>
    <li><label for="email_id">Email:</label></li>
    <li><%= f.email_field :email_id,:size=>30,:maxlength=>50 %></li>
     <li></li>
     <li><%= f.label :gender, "Male" %>
      <%= f.radio_button :gender,'Male', checked: true%>
       <%= f.label :gender, "Female" %>
      <%= f.radio_button :gender, 'Female'%></li>
     <li></li>
    <li><label for="dob">DOB:</label></li>
    <li><%= f.date_select :dob,:size=>10,:maxlength=>50,:start_year=>1911 %></li>
     <li></li>
    <li><label >BloodGroup:</label></li>
    <li>
    <%= f.select :bloodgrp, options_for_select(%w[A+ A- B+ B- AB+ AB- O+ O- A1+ A1- A2+ A2- A1B+ A1B- A2B+ A2B- BombayBloodGroup]) %>
    </li>
     <li></li>
    <li><label >MobileNo:</label></li>
    <li><%= f.text_field :mobno,:size=>15,:maxlength=>10 %></li>
     <li></li>
    <li><label for="address">Address:</label></li>

    <li><%= f.text_area :address,:size=>100,:maxlength=>100 %></li>
     <li></li>
     <li></li>
    <li><label >State:</label></li>
    <li>
      <%= f.select :state, options_for_select(%w[AndamanandNicobarIslands
      AndhraPradesh
      ArunachalPradesh
      Assam
      Bihar
      Chandigarh
      Chhattisgarh
      DadraandNagar Haveli
      DamanandDiu
      Delhi
      Goa
      Gujarat
      Haryana
      HimachalPradesh
      JammuandKashmir
      Jharkhand
      Karnataka
      Kerala
      Lakshadweep
      MadhyaPradesh
      Maharashtra
      Manipur
      Meghalaya
      Mizoram
      Nagaland
      Odisha
      Puducherry
      Punjab
      Rajasthan
      Sikkim
      TamilNadu
      Telengana
      Tripura
      UttarPradesh
      Uttarakhand
      WestBengal

      ]) %>
    </li>

     <li></li>
    <li><label>City:</label></li>
    <li><%= f.text_field :city,:size=>15,:maxlength=>15 %></li>
     <li></li>
    <li><label>PIN Code:</label></li>
    <li><%= f.text_field :pincode,:size=>15,:maxlength=>6 %></li>

    <%= f.submit(value='Register')%>

  </ul>
      </div>

      <% if @blood.errors.any? %>
          <div class="error" id="error_explanation">
            <h2>
              <%= pluralize(@blood.errors.count, "error") %>

            </h2>
            <ul>
              <% @blood.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
<% end %>

</body>
</html>

app/views/bloods/show.html.erb
<html>
<body>

<h1>Available Blood Donors</h1>
<style>
    .home{

        margin-left:1100px;

        font-weight: bold;
        font-size: large;
        font-style: inherit;
    }
    table{

        width:98%;
        margin-left: 10px;


    }
    th, td {
        padding: 5px;
        text-align: left;
    }
    table tr:nth-child(even) {
        background-color: #eee;
    }
    table tr:nth-child(odd) {
        background-color:#fff;
    }
    table th	{
        background-color: black;
        color: white;
    }
</style>
<a class="home" href="http://localhost:3000">Home</a>
<table >
  <tr>
    <th>FirstName</th>
    <th>LastName</th>
    <th>Email_ID</th>
    <th>Gender</th>
    <th>DOB</th>
    <th>Mobile.No</th>
    <th>Address</th>
    <th>City</th>
    <th>Pincode</th>
  </tr>

  <% @bloods.each do |blood| %>
      <tr>
        <td><%= blood.firstname %></td>
        <td><%= blood.lastname %></td>
        <td><%= blood.email_id %></td>
        <td><%= blood.gender %></td>
        <td><%= blood.dob %></td>
        <td><%= blood.mobno %></td>
        <td><%= blood.address %></td>
        <td><%= blood.city %></td>
        <td><%= blood.pincode %></td>
      </tr>
  <% end %>
</table>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blood</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield%>

</body>
</html>

app/views/welcome/index.html.erb
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
  <title>Black and White a Education and Books Category Flat Bootstarp Resposive Website Template | Home :: w3layouts</title>
  <link href="/assets/style.css" rel="stylesheet" type="text/css" media="all" />
  <link href="/assets/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,700,500italic,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,300,200,500,600,700,800,900' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
  <!-- js -->
  <script src="/assets/jquery.min.js"></script>
  <!-- //js -->
  <!-- for-mobile-apps -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="Black and White Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
  <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
  function hideURLbar(){ window.scrollTo(0,1); } </script>
  <!-- //for-mobile-apps -->
  <!-- start-smoth-scrolling -->
  <script type="text/javascript" src="/assets/move-top.js"></script>
  <script type="text/javascript" src="/assets/easing.js"></script>
  <script type="text/javascript">
      jQuery(document).ready(function($) {
          $(".scroll").click(function(event){
              event.preventDefault();
              $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
          });
      });
  </script>
  <!-- start-smoth-scrolling -->
  <!-- hover-effects -->
  <link href="/assets/hover.css" rel="stylesheet" media="all">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" media="all">
  <!-- //hover-effects -->
</head>

<body>
<!-- banner -->
<!-- header -->
<div class="banner">
  <div class="header">
    <div class="container">
      <div class="banner-nav">
        <span class="menu"><img src="assets/menu.png"/></span>
        <ul class="nav1">
          <nav class="cl-effect-3">
            <li><a href="http://localhost:3000/" class="act">Home</a></li>

            <li><a class="scroll" href="#team">Team</a></li>
            <li><a href="http://localhost:3000/bloods/new">Blood Donor Register</a></li>
            <li><a class="scroll" href="#services">Services</a></li>
            <li><a href="http://localhost:3000/bloods/find">Find a Blood Donor</a></li>
            <li><a class="scroll" href="#contact">Contact Us</a></li>

          </nav>
        </ul>

        <div class="logo">
          <a href="http://localhost:3000/"><img src="assets/logo.png"/></a>
        </div>
      </div>
      <!-- script for menu -->
      <script>
          $( "span.menu" ).click(function() {
              $( "ul.nav1" ).slideToggle( 300, function() {
                  // Animation complete.
              });
          });
      </script>
      <!-- //script for menu -->
    </div>
  </div>
  <!-- //header-->
  <!-- Slider-starts-Here -->
  <script src="/assets/responsiveslides.min.js"></script>
  <script>
      // You can also use "$(window).load(function() {"
      $(function () {
          // Slideshow 4
          $("#slider3").responsiveSlides({
              auto: true,
              pager: true,
              nav: false,
              speed: 500,
              namespace: "callbacks",
              before: function () {
                  $('.events').append("<li>before event fired.</li>");
              },
              after: function () {
                  $('.events').append("<li>after event fired.</li>");
              }
          });

      });
  </script>
  <!--//End-slider-script -->
  <div  id="top" class="callbacks_container">
    <ul class="rslides" id="slider3">
      <li>
        <div class="banner-info">
          <h3>LOVE CARE AND HUMANITY</h3>
          <p>Together We can and Must Make a Difference</p>
          <div class="more">
            <a href="#services">READ MORE</a>
          </div>
        </div>
      </li>
      <li>
        <div class="banner-info">
          <h3>DONATE BLOOD</h3>
          <p>Donate Blood Save Life !</p>
          <div class="more">
            <a href="#services">READ MORE</a>
          </div>
        </div>
      </li>
      <li>
        <div class="banner-info">
          <h3>DONATE BLOOD</h3>
          <p>Donate Blood Save Life !</p>
          <div class="more">
            <a href="#services">READ MORE</a>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>
<!-- //banner -->
<!-- banner-bottom -->
<div id="services" class="banner-bottom">
  <div class="container">
    <div class="banner-bottom-left">
      <div class="year1">
        <h3>2011</h3>
        <p>We had our Inauguration function !!!
          <span>We had the Afforestation mission on the same day planted 250 tree sapling's</span></p>
      </div>
      <div class="year-pos">
        <img src="assets/1.png"/>
      </div>
      <div class="year1 year3">
        <h3>2013</h3>
        <p>Initiative to Plastic free Pollachi!!!
          <span>More than 100 kg's of plastic is not a simple thing to let it sediment... </span>
          <span>We did a Great JOB</span> </p>
      </div>
      <div class="year-pos1">
        <img src="assets/2.png"/>
      </div>
    </div>
    <div class="banner-bottom-right">
      <div class="year1 year2">
        <h3>2012</h3>
        <p>Organ Donation Campaign PROJECT NAME : UYIREH PETTROM !!!
          <span>150 Infinities have proved their desire to "LIVE AFTER THEIR DEATH"...</span>
          <span>We Infinities Proved once again.</span></p>
      </div>
      <div class="year-pos2">
        <img src="assets/3.png"/>
      </div>
      <div class="year1 year4">
        <h3>2014</h3>
        <p>INFINITY CRICKET TROPHY !!!
          <span>With the entry fee, We educated 25 children's</span>
        </p>
      </div>
      <div class="year-pos3">
        <img src="assets/4.png"/>
      </div>
    </div>

  </div>
  <div class="grid-bann">
    <span> </span>
  </div>
  <div class="clearfix"> </div>
</div>
<!-- //banner-bottom -->
<!-- team -->
<div id="team" class="team">
  <div class="container">
    <h3>This is our team</h3>
    <p class="para">We are small but effective </p>
    <div class="team-grid1 start">
      <div class="team-fig">
        <span> </span>
      </div>
      <h4>Preyes M</h4>
      <p style="font-weight: Bold">Treasurer & CEO</p>
      <ul>
        <li><a href="#" class="twitter"> </a></li>
        <li><a href="#" class="instagram"> </a></li>
      </ul>
    </div>
    <div class="team-grids">
      <div class="team-grid start">
        <div class="team-fig1">
          <span> </span>
        </div>
        <h4>Sreeram Mohan</h4>
        <p style="font-weight: Bold">Secretary</p>
        <ul>
          <li><a href="#" class="twitter"> </a></li>
          <li><a href="#" class="instagram"> </a></li>
        </ul>
      </div>
      <div class="team-grid start">
        <div class="team-fig2">
          <span> </span>
        </div>
        <h4>Aravindha Vasanth Ram</h4>
        <p style="font-weight: Bold">Member Trustee</p>
        <ul>
          <li><a href="#" class="twitter"> </a></li>
          <li><a href="#" class="instagram"> </a></li>
        </ul>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>
<!-- //team -->
<!-- blog -->
<div class="blog">
  <div class="container">
    <h3>Save a Life , Donate Blood</h3>
    <p class="para1">  No one has ever become poor by giving!!!</p>
    <div class="blog-grids">
      <div class="blog-grid">
        <div class="blog-fig figure">
          <span> </span>
        </div>
        <h4>Our Vision</h4>
        <p>Secured progress among the under secured.</p>
      </div>
      <div class="blog-grid">
        <div class="blog-fig figure1">
          <span> </span>
        </div>
        <h4>Our Motto</h4>
        <p>An INDIAN SERVICE with LOVE, CARE, and HUMANITY</p>
      </div>
      <div class="blog-grid">
        <div class="blog-fig figure2">
          <span> </span>
        </div>
        <h4>Our Mission</h4>
        <p>Successive provision’s to prosper our nation with genuine service. </p>
      </div>
      <div class="clearfix"> </div>
    </div>
    <div class="visit">

    </div>
  </div>
</div>
<!-- //blog -->
<!-- contact -->
<div id="contact" class="contact">
  <div class="container">
    <h3>Contact Us</h3>

    <div class="contact-grids">
      <div class="contact-grid">
        <div class="contact-fig">
          <span> </span>
        </div>
        <p>+91-9789216466</p>
      </div>
      <div class="contact-grid">
        <div class="contact-fig1">
          <span> </span>
        </div>
        <p>Infinity Trust,Pollachi-642001</p>
      </div>
      <div class="contact-grid">
        <div class="contact-fig2">
          <span> </span>
        </div>
        <p><a href="mailto:info@example.com">infinitiesworld@gmail.com</a></p>
      </div>
      <div class="clearfix"> </div>
    </div>
    <%= form_for :comment ,url: {action: "create"} do |f| %>


        <%= f.text_field :name,:size=>30,:maxlength=>15,:placeholder=>'FullName' %>
        <br>

        <%= f.text_field :email_id,:size=>30,:maxlength=>50,:placeholder=>'Email ID' %>
        <br>

        <%= f.text_field :number,:size=>15,:maxlength=>10,:placeholder=>'Mobile No' %>
        <br>

        <%= f.text_area :text,:size=>15,:maxlength=>50,:placeholder=>'Write your Message here..' %>
        <br>

        <%= f.submit(value:"Submit") %>

        <% if @comment.errors.any? %>
            <div class="error" id="error_explanation">
              <h2>
                <%= pluralize(@comment.errors.count, "error") %>

              </h2>
              <ul>
                <% @comment.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
    <% end %>

  </div>
</div>
<!-- //contact -->
<!-- footer -->
<div class="footer">
  <div class="container">

  </div>
</div>
<!-- //footer -->
<!-- here stars scrolling icon -->
<script type="text/javascript">
    $(document).ready(function() {
        /*
         var defaults = {
         containerID: 'toTop', // fading element id
         containerHoverID: 'toTopHover', // fading element hover id
         scrollSpeed: 1200,
         easingType: 'linear'
         };
         */

        $().UItoTop({ easingType: 'easeOutQuart' });

    });
</script>
<!-- //here ends scrolling icon -->
</body>
</html>